export const COLOR_MAP: { [status: string]: string } = {
  BOOTSTRAPPING: 'good',
  CANCELED: 'warning',
  CANCELLING: 'warning',
  CANCEL_PENDING: 'good',
  COMPLETED: 'good',
  DELAYED: 'good',
  FAILED: 'danger',
  FAULT: 'danger',
  IN_PROGRESS: 'good',
  INPROGRESS: 'good',
  INTERRUPTED: 'danger',
  PENDING: 'good',
  QUEUED: 'good',
  RUNNING: 'good',
  STARTED: 'good',
  STARTING: 'good',
  STOPPED: 'warning',
  SUCCESS: 'good',
  SUCCEEDED: 'good',
  TERMINATED: 'good',
  TERMINATED_WITH_ERRORS: 'danger',
  TERMINATING: 'good',
  TIMEDOUT: 'danger',
  TIMED_OUT: 'danger',
  WAITING: 'good',
};
